### ISSUE TITLE
Exceptions when clicking on a command sign

### ISSUE THREAD

**Issue by Bloodlex** [Geitenijs/CommandBlocks#11]
**Describe the bug**
I'm getting exceptions when clicking on a sign.

Link to pastebin with this exception: [https://pastebin.com/kD4LAVk8](https://pastebin.com/kD4LAVk8)
Block configuration: [https://pastebin.com/WeSwUT39](https://pastebin.com/WeSwUT39)
Config configuration: [https://pastebin.com/4fbL6xcr](https://pastebin.com/4fbL6xcr)

**To Reproduce**
1. Create a sign
2. Attach a command to signs
3. See error on the console

**Expected behavior**

**Environment (please complete the following information):**
 - Linux
 - Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - 1.16.5

Plugins: 
Plugins (67): ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterBees, BetterHeads, CommandBlocks, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, dynmap*, Dynmap-WorldGuard*, EasyCarts, Epidemic, Essentials, EssentialsChat, GoldenEnchants, GSit, Harbor, HolographicDisplays, Images, InteractiveBooks, JetsAntiAFKPro, Jobs, KeepChunks, LangUtils, Lasso, LastLoginAPI, LeaderHeadsRevamped, LogBlock, LuckPerms, LWC, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, Orebfuscator, PetMaster, Pingas*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, RegionRaid, SAML, SkinsRestorer, Spartan, SuperVanish, TAB, TitleManager, TreeAssist, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by Geitenijs** [comment]
Works fine for me.. Probably a conflicting plugin?
