### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by AdamDAuria** [Geitenijs/CommandBlocks#15]
**Describe the bug**
everytime  you run a command it spam in the console

**To Reproduce**
1. step on a pressure plate 
2. Get telported
3. Spam in the console

**Expected behavior**
Spam

**Screenshots**
06.10 03:31:46 [Server] WARN Task #180712 for CommandBlocks v1.2.7 generated an exception
06.10 03:31:46 [Server] INFO java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
06.10 03:31:46 [Server] INFO at com.geitenijs.commandblocks.Events.lambda$onCommandBlockInteract$0(Events.java:122) ~[CommandBlocks-1.2.7.jar:?]
06.10 03:31:46 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-283]
06.10 03:31:46 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]

**Environment (please complete the following information):**
 - OS: Linux
 - Server Software Paper
 - Server Version 1.17.1
 - Full list of plugins

![2021-10-05_02 22 13](https://user-images.githubusercontent.com/87257360/136136952-49730721-4dbb-4d67-84e4-3e0391966eef.png)

![2021-10-05_02 22 23](https://user-images.githubusercontent.com/87257360/136136969-18ba7cd9-a6b0-4b8d-9648-1ac4fb9a2855.png)

**Additional context**

**Comment by Geitenijs** [comment]
Check your config please
