### ISSUE TITLE
Plugin not working on signs

### ISSUE THREAD

**Issue by Folas1337** [Geitenijs/CommandBlocks#16]
**Describe the bug**
It seems like the plugin no longer works on signs while it did for a while :(

There are no errors or anything, I just used it on a server with no other plugins, installed it, created a command block on a sign but it does nothing on right click. Would be cool if you could look into this :)

Replacing the sign with another block works fine though.

**To Reproduce**
Install paper, install plugin, run paper, create command block on a sign and see no effect on right click.

**Expected behavior**
A message saying "This requires you to have Vault installed." because I currently don't but at least it would tell me it's working.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Server Software: Paper
 - Server Version: 1.18.2
 - Full list of plugins: ViaVersion, ViaBackwards, CommandBlocks

**Additional context**
I've tried contacting you on spigot forums before but with no luck (I thought it was not working at all but just now realized it works on regular blocks) https://www.spigotmc.org/threads/commandblocks.348866/page-3#post-4384291

**Comment by Geitenijs** [comment]
Will look into it soon. Apologies for not responding to you before!

**Comment by Geitenijs** [comment]
I just checked this on Paper 1.18.2 and 1.19, seems to work fine for me. ViaVersion/ViaBackwards could be the problem, can you please check it without those plugins?

**Comment by Folas1337** [comment]
> I just checked this on Paper 1.18.2 and 1.19, seems to work fine for me. ViaVersion/ViaBackwards could be the problem, can you please check it without those plugins?

I had it reproduced on a server with no other plugins... by now I've replaced the plugin on my server though and I don't really need this anymore.
If nobody else is having this problem and you want me to close this issue, I can do so, otherwise you can experiment around if you want to and close it once this is done. I honestly don't care that much anymore, sorry...

**Comment by Folas1337** [comment]
I don't need this issue anymore as I've moved on to another plugin so I'll just close it.
Have a nice day :)
