### ISSUE TITLE
Files get reseted when upload the ftp files to update commands

### ISSUE THREAD

**Issue by eaeniko** [Geitenijs/CommandBlocks#3]
I've set a new command /cb create current test
then I've downloaded the file to edit the commands etc.
But when I try to upload the new file edited doesnt work. Then when I restart the server the file get reseted and all the commands I've created are gone. Every single time. Cant even test if the commands are working.

**Comment by Geitenijs** [comment]
Works fine for me. Try /cb reload after uploading blocks.yml
