### ISSUE TITLE
Permission negation / One time use

### ISSUE THREAD

**Issue by BlitzOffline** [Geitenijs/CommandBlocks#4]
Hello

I would like a feature similar to "permission:" but exactly the opposite of it. A permission negation.

Instead of checking the players for a permission and then allowing them to use the block it will check for the player to not have that permission and then allowing them to use the item.

If that wouldn't be possible then I would like a feature that allows me to set an block that can be clicked only one time and the second time nothing happens or it will just send a message.

**Comment by Geitenijs** [comment]
What's your permissions plugin? You can easily revoke permissions using a command with most plugins.

For example with LuckPerms, use "lp user {player} permission set {permission} false".

**Comment by BlitzOffline** [comment]
Yeah forgot about the false thing. Thank you very much
