### ISSUE TITLE
Add support for 1.8

### ISSUE THREAD

**Issue by Fabri4K** [Geitenijs/CommandBlocks#5]
**Is your feature request related to a problem? Please describe.**
Maybe, i wanna use this plugin, ive been searching for a long time and all i see is +1.12 plugins. but my server 1.8

**Describe the solution you'd like**
I want to use this plugin so i need 1.8 support

**Additional context**
Im using CrazyEnchantments and i want to be able to right click a block and see the menu (command: /crazyenchants)

**Comment by Geitenijs** [comment]
https://github.com/Geitenijs/CommandBlocks/releases/tag/v1.1.11

1.2.0 dropped support for versions below 1.13
