### ISSUE TITLE
Redstone powered detection

### ISSUE THREAD

**Issue by NobleStrike** [Geitenijs/CommandBlocks#9]
Currently the plugin requires a player to activate a "CommandBlock", could you make it so we could trigger them with redstone? It would basically add detection of the powered state of the block, and it would need to be able to trigger without a direct player interaction.

Actual Command Blocks cant run plugin commands, this plugin can, but is limited to player interaction triggers only.

Other than that, great plugin and hope to see this feature if its worth your time. Thank you

**Comment by Geitenijs** [comment]
Actual command blocks can definitely run plugin commands :) I used them for it all the time
